### Obtener todos los colores
GET http://localhost:4000/colores
Accept: application/json

###

### Crear un nuevo color
POST http://localhost:4000/colores/nuevo
Content-Type: application/json

{
  "r": 255,
  "g": 100,
  "b": 50
}

###

### Borrar un color (reemplaza <ID_DEL_COLOR> por el _id real)
DELETE http://localhost:4000/colores/borrar/<ID_DEL_COLOR>
Accept: application/json
