GET http://localhost:4000/colores 

###

POST http://localhost:4000/colores/nuevo
Content-Type: application/json

{
    "r": 20,
    "g": 10,
    "b": 15
}

####

DELETE http://localhost:4000/colores/borrar/68c2aac0f4078634fb3d1616

